version: '3.4'

services:
    cntlm:
        container_name: cntlm
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - USERNAME=empty
                - DOMAIN=empty
                - PASSWORD=empty
                - PROXIES=empty
        image: cntlm:v1.0
        ports:
            - 3128:3128
