version: '3.4'

services:
    cntlm:
        container_name: cntlm
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - USERNAME="testuser"
                - DOMAIN="corp-uk"
                - PASSWORD="password"
                - PROXY="10.0.0.41:8080"
                - NOPROXY=""
        image: cntlm:v1.0
        ports:
            - 3128:3128
